name: GDHooks
main: com.griefdefender.hooks.loader.BukkitLoaderPlugin
depend: [GriefDefender]
softdepend: [BlueMap, BossShopPro, ChestShop, CustomItems, Dynmap, DynamicShop, InsaneShops, mcMMO, MyPet, MMOItems, MythicMobs, QuickShop, RevoltCrates, Shop, ShopChest, SimpleClans, Slabbo, Towny, UltimateShops]
load: POSTWORLD
version: '0.4'
api-version: 1.13
